environment: prod
database:
  host: prod-db-host
  port: 5432
  name: investment_db
  user: ${DB_USER}
  password: ${DB_PASSWORD}

server:
  port: 8080
  host: 0.0.0.0

market_data:
  update_interval: 5m