name: Docker Build and Publish

on:
  push:
    tags:
      - 'v*'      # Production releases
      - 'dev-v*'  # Development releases

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Проверка кода из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment
        id: set-env
        run: |
          if [[ ${{ github.ref_name }} == dev-v* ]]; then
            echo "BUILD_ENV=dev" >> $GITHUB_ENV
          elif [[ ${{ github.ref_name }} == v* ]]; then
            echo "BUILD_ENV=prod" >> $GITHUB_ENV
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/investment-tracker:${{ github.ref_name }}
          build-args: |
            ENV=${{ env.BUILD_ENV }}